/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import alertUI from "./script/alertUI"
import gamevoerUI from "./script/gamevoerUI"
import HomeUI from "./script/HomeUI"
import rankingUI from "./script/rankingUI"
import SignUI from "./script/SignUI"
import StartUI from "./script/StartUI"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/Start.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/alertUI.ts",alertUI);
        reg("script/gamevoerUI.ts",gamevoerUI);
        reg("script/HomeUI.ts",HomeUI);
        reg("script/rankingUI.ts",rankingUI);
        reg("script/SignUI.ts",SignUI);
        reg("script/StartUI.ts",StartUI);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();