/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import StartUI from "./script/StartUI"
import GameUI from "./script/GameUI"
import SignUI from "./script/SignUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="test/signUI.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/StartUI.ts",StartUI);
        reg("script/GameUI.ts",GameUI);
        reg("script/SignUI.ts",SignUI);
    }
}
GameConfig.init();